[package]
name = "orthodb_request"
version = "0.1.0"
authors = ["amsesk <amsesk@umich.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.18"
clap = "3.2.12"
serde_json = "1.0.82"